baseURL = "/"
title = "Xdi8 Aho"

theme = "docsy"

contentDir = "content/art-x-xdi8"
defaultContentLanguage = "art-x-xdi8"
defaultContentLanguageInSubdir = false

[languages]
[languages.art-x-xdi8]
title = "Xdi8 aho"
description = ""
languageName = "ğŸŒ Xdi8"
contentDir = "content/art-x-xdi8"
time_format_default = "2021-01-16"
time_format_blog = "2021-01-16"

[languages.cmn-Hans]
title = "å¸Œé¡¶è¯­"
description = ""
languageName = "ğŸŒ ä¸­æ–‡"
contentDir = "content/cmn-Hans"
time_format_default = "2021-01-16"
time_format_blog = "2021-01-16"

[languages.en]
title = "Shidinn Language"
description = ""
languageName ="ğŸŒ English"
contentDir = "content/en"
time_format_default = "2021-01-16"
time_format_blog = "2021-01-16"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[[menu.main]]
    name = "Wiki"
    weight = 50
    url = "https://wiki.xdi8.top"

[languages.art-x-xdi8.params.links]
[[languages.art-x-xdi8.params.links.user]]
	name = "â‡§xdi8 â‡§nfi25iYi4oquV"
	url = "http://xdi8translator.nyoeghau.com/"
	icon = "fa fa-language"
        desc = "â‡§xdi8 â‡§nfi25iYi4oquV"

[[languages.art-x-xdi8.params.links.user]]
  	name = "â€¹â‡§bEr1sEbEr1sEâ€º rT de â‡§utA46H â‡§pzTrL"
  	url = "https://b23.tv/PAJnPD"
  	icon = "fab fa-youtube"
        desc = "Bilibili ä¸Šçš„å¸Œé¡¶ç¤¾åŒº"

[[languages.art-x-xdi8.params.links.developer]]
	name = "â‡§b8fz2 de â€¹â‡§gEtâ‡§habâ€º â‡§DuTkA"
	url = "https://github.com/xdi8/xdi8.github.io"
	icon = "fab fa-github"
        desc = "æœ¬ç«™çš„ GitHub ä»“åº“"

[languages.cmn-Hans.params.links]
[[languages.cmn-Hans.params.links.user]]
	name = "å¸Œé¡¶ç¿»è¯‘å™¨"
	url = "http://xdi8translator.nyoeghau.com/"
	icon = "fa fa-language"
        desc = "å¸Œé¡¶ç¿»è¯‘å™¨"

[[languages.cmn-Hans.params.links.user]]
  	name = "Bilibili ä¸Šçš„å¸Œé¡¶ç¤¾åŒº"
  	url = "https://b23.tv/PAJnPD"
  	icon = "fab fa-youtube"
        desc = "Bilibili ä¸Šçš„å¸Œé¡¶ç¤¾åŒº"

[[languages.cmn-Hans.params.links.developer]]
	name = "æœ¬ç«™çš„ GitHub ä»“åº“"
	url = "https://github.com/xdi8/xdi8.github.io"
	icon = "fab fa-github"
        desc = "æœ¬ç«™çš„ GitHub ä»“åº“"

[languages.en.params.links]
[[languages.en.params.links.user]]
	name = "Shidinn Translator"
	url = "http://xdi8translator.nyoeghau.com/"
	icon = "fa fa-language"
        desc = "å¸Œé¡¶ç¿»è¯‘å™¨"

[[languages.en.params.links.user]]
  	name = "Shidinn Community on Bilibili"
  	url = "https://b23.tv/PAJnPD"
  	icon = "fab fa-youtube"
        desc = "Bilibili ä¸Šçš„å¸Œé¡¶ç¤¾åŒº"

[[languages.en.params.links.developer]]
	name = "GitHub Repository of This Site"
	url = "https://github.com/xdi8/xdi8.github.io"
	icon = "fab fa-github"
        desc = "æœ¬ç«™çš„ GitHub ä»“åº“"

